config/routes.rb
Rails.application.routes.draw do
  resource :turbo_stream_demo, only: :show

  resources :posts, only: [:create, :index] do
    resources :likes, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  validates :body, length: { minimum: 1, maximum: 280 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id]).increment(:likes_count)
    @post.save

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("post_#{@post.id}", partial: 'posts/post', locals: { post: @post })
      end
      format.html { redirect_to turbo_stream_demo_path }
      end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where("likes_count > 0")
    @post = Post.new
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace(:posts, partial: 'posts/post', collection: @posts ) }
      format.html { render template: 'turbo_stream_demos/show' }
    end
  end

  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.prepend('posts', partial: 'posts/post', locals: { post: @post }),
            turbo_stream.replace(:new_post, partial: 'turbo_stream_demos/form', locals: { post: Post.new })
          ]
        end
        format.html { redirect_to turbo_stream_demo_path }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            :new_post, partial: 'turbo_stream_demos/form', locals: { post: @post }
          )
        end
        format.html {
          @posts = Post.all.order(created_at: :desc)
          render template: 'turbo_stream_demos/show'
        }
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/turbo_stream_demos_controller.rb
class TurboStreamDemosController < ApplicationController
  def show
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-turbo='false'>
  <head>
    <title>TurboDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= yield :head %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="card mb-2" id="<%= dom_id(post) %>">
  <div class="card-body">
    <h5 class="card-title text-muted">
      <small class="float-right">
        Posted at <%= post.created_at %>
      </small>
    </h5>
    <div class="card-text lead mb-2"><%= post.body %></div>
    <%= button_to post_likes_path(post),
      form: { data: { 'controller': 'turbo-form' } },
      class: 'card-link btn btn-secondary btn-sm',
      data: { 'turbo-form-target': 'submitInput' } do %>
        Likes (<%= post.likes_count %>)
    <% end %>
  </div>
</div>

app/views/turbo_stream_demos/_form.html.erb
<%= form_with model: post, url: posts_path, id: dom_id(post), html: { class: 'my-4', data: { controller: 'turbo-form' } } do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:
      </h2>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_area :body, placeholder: 'Enter your post', class: 'form-control', rows: 3 %>
  </div>

  <div class="actions my-2">
    <%= f.submit class: "btn btn-primary", data: { 'turbo-form-target': 'submitInput' } %>
  </div>
<% end %>

app/views/turbo_stream_demos/show.html.erb
<div class="container my-5">
  <h1>Turbo Streams Demo</h1>

  <%= render partial: 'turbo_stream_demos/form', locals: { post: @post } %>

  <%= button_to 'GET PostsController#index',
                posts_path,
                method: :get,
                class: 'btn btn-success',
                form: { data: { controller: 'turbo-form' } },
                data: { 'turbo-form-target': 'submitInput' } %>

  <div id='posts'>
    <%= render @posts %>
  </div>
</div>